swagger: "2.0"
info:
  description: "api demo"
  version: "1.0.0"
  title: "Paperwall"

host: "api.stemaker.top"
basePath: "/"
tags:
- name: "message"
  description: "Everything about your Messages"
- name: "comment"
  description: "Everything about your Comments"
- name: "user"
  description: "Operations about user"
schemes:
- "https"
- "http"
# APIs starts from here
paths:
  /message:
    get:
      tags:
      - "message"
      summary: "get existing messages"
      description: "default to get latest"
      operationId: "getMessages"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
        404: 
          description: "Not Found"

    post:
      tags:
      - "message"
      summary: "Add a new message"
      description: ""
      operationId: "addMessage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Message object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Message"
      responses:
        405:
          description: "Invalid input"

  /message/{msgId}:
    get:
      tags:
      - "message"
      summary: "get a message by _id"
      description: ""
      operationId: "getMessage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
          
    delete:
        tags:
        - "message"
        summary: "Delete a new message"
        description: ""
        operationId: "deleteMessage"
        consumes:
        - "application/json"
        produces:
        - "application/json"
  
  /comment/{msgId}:
    get:
      tags:
      - "comment"
      summary: "Get comments"
      description: "Get comments by message id"
      operationId: "getCommentsByMessage"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
    post:
      tags:
      - "comment"
      summary: "Create new comment"
      description: "Create new comment under message"
      operationId: "createComment"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
    
  /comment/{comId}:
    delete:
      tags:
      - "comment"
      summary: "Delete comment by id"
      description: "Delete comment"
      operationId: "deleteComment"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
 
  /user:
    post:
      tags:
      - "user"
      summary: "Create new user"
      description: "Gets session key unionId and openId from wechat adn save to database."
      operationId: "createUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object" 
        required: true
        schema:
          $ref: "#/definitions/CreateUser"
      - in: "query"
        name: "name"
        description: "Created user object" 
        required: true
        schema:
          $ref: "#/definitions/CreateUser"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SuccessfulCreatedUser"

  /user/{userId}:
    get:
      tags:
      - "user"
      summary: "Get user by user id"
      description: ""
      operationId: "getUserById"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "The name that needs to be fetched. Use user1 for testing. "
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"

    put:
      tags:
      - "user"
      summary: "update user info"
      description: ""
      operationId: "updateUser"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "body"
        description: "The user name for login"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
  
  /like/{type}/{id}:
    post:
      tags:
      - "like"
      summary: "Create new like"
      description: ""
      operationId: "createLike"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "user"
        description: "Created user object" 
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/NotOK"
        400:
          description: ""

    delete:
      tags:
      - "like"
      summary: "cancel like"
      description: ""
      operationId: "deleteLike"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object" 
        required: true
        schema:
          $ref: "#/definitions/NotOK"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/NotOK"

  /notification/{userId}:
    get:
      tags:
      - "notification"
      summary: "get existing notifications"
      description: ""
      operationId: "getNotifications"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "The name that needs to be fetched. Use user1 for testing. "
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
      
  /notification/{id}:
    put:
      tags:
      - "notification"
      summary: "update notification"
      description: "update notificaiton based on id"
      operationId: "updateNotifications"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "notification"
        description: "Created notificaiton object" 
        required: true
        schema:
          $ref: "#/definitions/Notification"
      
      

definitions:
  # post body for /user
  CreateUser:
    type: "object"
    properties:
      username:
        type: "string"
      openId:
        type: "string"
      unionId:
        type: "string"
      userInfo:
        type: "object"
        properties:
          gender: 
            type: "string"
            example: "f"
          major:
            type: "string"
          grade:
            type: "string"

  # response for /user
  SuccessfulCreatedUser:
    type: "object"
    properties:
      _id: 
        type: "string"

  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "User Status"

  Message:
    type: "object"
    required:
    - "user"
    - "createdAt"
    properties:
      _id:
        type: "string"
      content:
        type: "string"
      location:
        type: "string"
        example: "IR"
      tags:
        type: "array"
        items:
          type: "string"
      status:
        type: "string"
        description: "pet status in the store"
        enum:
        - "available"
        - "pending"
        - "sold"
  NotOK:
    type: "object"
    properties:
      notFinish:
        type: "string"
        example: "To be continue"